# Generated by Django 5.2.1 on 2025-05-23 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.BigIntegerField(unique=True)),
                ('url', models.CharField(max_length=2000)),
                ('img', models.CharField(blank=True, max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('hidden', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('file_type', models.CharField(max_length=20)),
                ('space_providers', models.JSONField(blank=True, default=list)),
                ('used_size', models.BigIntegerField(blank=True, default=None, null=True)),
                ('real_position', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('account', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('picture', models.URLField(blank=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.BigIntegerField(blank=True, default=None, null=True)),
                ('children_id', models.JSONField(blank=True, default=list)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_structure', to='api.bookmarks')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_structure', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_account', models.EmailField(max_length=254)),
                ('provider_name', models.CharField(max_length=200)),
                ('provider_picture', models.URLField(blank=True)),
                ('access_token', models.CharField(blank=True, max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='api.user'),
        ),
    ]
