# Generated by Django 5.2.1 on 2025-05-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='space_providers',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
