# Generated by Django 5.2.1 on 2025-05-23 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bookmarks_space_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='treestructure',
            name='bookmark_foreignkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tree_structure', to='api.bookmarks'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treestructure',
            name='bid',
            field=models.BigIntegerField(),
        ),
    ]
