# Generated by Django 5.2.1 on 2025-05-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_treestructure_bookmark_foreignkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='access_token',
            field=models.TextField(blank=True),
        ),
    ]
