# Generated by Django 5.2.1 on 2025-05-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_provider_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='bid',
            field=models.BigIntegerField(),
        ),
    ]
