# Generated by Django 5.2.1 on 2025-05-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_bookmarks_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarks',
            name='real_position',
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='google_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='google_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='total_size',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
