# Generated by Django 5.2.1 on 2025-05-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_bookmarks_real_position_bookmarks_google_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='refresh_token',
            field=models.TextField(blank=True),
        ),
    ]
