# Generated by Django 5.2.1 on 2025-05-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_provider_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='used_size',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
