services:
  frontend:
    build: ../frontend
    ports:
      - "5174:5174"
    volumes:
      - ../frontend:/app/frontend
      - /app/frontend/node_modules
    command: npm run dev

  backend:
    build: ../backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
      - /app/node_modules
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: bookmarks
      POSTGRES_USER: team15
      POSTGRES_PASSWORD: '16'
    ports:
      - "5432:5432"
    volumes:
      - ../postgres:/var/lib/postgresql/data
